### ISSUE TITLE
Template update 

### ISSUE THREAD

**Issue by rickgrimm** [aws-samples/aws-cft-digital-preservation-archivematica-on-aws#5]
Please update the template to Archivematica 1.15.0 and support for Ubuntu 22.04 or Rocky Linux 9:

https://www.archivematica.org/en/docs/archivematica-1.15/admin-manual/installation-setup/installation/installation/

Thanks!

**Comment by awsjab** [comment]
Thanks Rick!

We're currently looking into the following:
- [ ] Adding support for Archivematica 1.15.0 + Ubuntu 22.04 or Rocky Linux 9
- [ ] Adding support for Amazon EC2 Graviton2/3 (ARM64) for additional performance efficiency and cost optimization
- [ ] Releasing the Cloud Development Kit (CDK) code

**Comment by awsjab** [comment]
We have upgraded this solution to include an Archivematica 1.15.x deployment on Ubuntu 22.04. We will release the upgraded solution to a new GitHub repository in the coming months. In the meantime, please let us know if you have a need to deploy the upgraded solution before it's published to GitHub. Rick has already deployed the upgraded solution.
